name: my_r_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base=4.3.0
  - r-tidyverse
  - r-devtools
  - r-curl
  - r-data.table
  - r-readr
  - r-dplyr
  - r-purrr
  - r-httr
  - r-rmarkdown
  - r-knitr
  - r-downloader
  - r-rio
  - pip:
    - jupyter
